In [1]:
%pip install pandas scikit-learn seaborn matplotlib

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: numpy>=2.3.3 in .\Virtual_env\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\Virtual_env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\Virtual_env\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.10.0 in .\Virtual_env\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in .\Virtual_env\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\Virtual_env\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\Virtual_env\Lib\site-packages (from scikit-learn) (3.6.0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: cycler>=0.10 in .\Virtual_env\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\Virtual_env\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\Virtual_env\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\Virtual_env\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in .\Virtual_env\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\Virtual_env\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\Virtual_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Installing collected packages: contourpy, scikit-learn, pandas, matplotlib, seaborn

   ---------------------------------------- 0/5 [contourpy]
   ---------------------------------------- 0/5 [contourpy]
   ---------------------------------------- 0/5 [contourpy]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]
   ---------------- ----------------------- 2/5 [pandas]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Housing.csv")

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [6]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB